#!/usr/bin/env python3
"""Generates qt/emoji_data.h from the Unicode emoji-test.txt (Debian: /usr/share/unicode/emoji/emoji-test.txt).
Only fully-qualified emoji without skin-tone variants; one entry per emoji with its CLDR short name and group."""
import re, sys

src = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/unicode/emoji/emoji-test.txt"
groups, items = [], []
group = -1
for line in open(src, encoding="utf-8"):
    line = line.rstrip("\n")
    if line.startswith("# group:"):
        groups.append(line.split(":", 1)[1].strip())
        group = len(groups) - 1
        continue
    if not line or line.startswith("#"):
        continue
    m = re.match(r"^([0-9A-F ]+)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E[0-9.]+\s+(.*)$", line)
    if not m:
        continue
    cps, glyph, name = m.group(1), m.group(2), m.group(3)
    if "skin tone" in name or "hair" in name and "person:" in name:
        continue
    if group < 0 or groups[group] == "Component":
        continue
    items.append((glyph, name, group))

def cstr(s):
    return '"' + "".join("\\%03o" % b if b >= 0x80 or b < 0x20 or chr(b) in '"\\' else chr(b) for b in s.encode("utf-8")) + '"'

with open("qt/emoji_data.h", "w") as f:
    f.write("/* Generated by scripts/gen_emoji.py from Unicode emoji-test.txt: do not edit. */\n#ifndef VC_QT_EMOJI_DATA_H\n#define VC_QT_EMOJI_DATA_H\n\n")
    names = [g for g in groups if g != "Component"]
    f.write("static const char *const EMOJI_GROUPS[] = {%s};\n" % ", ".join(cstr(g) for g in names))
    f.write("struct EmojiItem { const char *glyph, *name; unsigned char group; };\n")
    f.write("static const EmojiItem EMOJI_ITEMS[] = {\n")
    for glyph, name, g in items:
        f.write("    {%s, %s, %d},\n" % (cstr(glyph), cstr(name), g))
    f.write("};\n#endif\n")
print(len(items), "emoji in", len(groups) - 1, "groups")
